#!/bin/bash
echo "Apagando os arquivos antigos!!!"
#rm /Users/williammoura/Desenv/etiquetas-personalizadas/links-api/*.*
echo "Copiando arquivos atuais de agora!!!"
find . | egrep "src|public|controllers|routes" |egrep -v "backup|post|node|fonts|images|Store|bkp|old|2024|outros" |egrep "js|css"| xargs -I{} cp {} /Users/williammoura/Desenv/etiquetas-personalizadas/links-api/
echo "Arquivos copiados. Boa diversão"
